from enum import Enum

class animalType(Enum):
    DOG = 1
    CAT = 2
    PIG = 3
    RABBIT = 4

FIELD_NAME_ID = "Id"
FIELD_NAME_CATEGORY = "Category"
FIELD_NAME_NAME = "Name"
FIELD_NAME_AGE = "Age"

def getAnimalData():
    return [
        {FIELD_NAME_ID:1, FIELD_NAME_CATEGORY:animalType.DOG.value,FIELD_NAME_NAME:"DOG-A", FIELD_NAME_AGE:9},
        {FIELD_NAME_ID:2, FIELD_NAME_CATEGORY:animalType.DOG.value,FIELD_NAME_NAME:"DOG-B", FIELD_NAME_AGE:5},
        {FIELD_NAME_ID:3, FIELD_NAME_CATEGORY:animalType.DOG.value,FIELD_NAME_NAME:"DOG-C", FIELD_NAME_AGE:7},
        {FIELD_NAME_ID:4, FIELD_NAME_CATEGORY:animalType.CAT.value,FIELD_NAME_NAME:"CAT-A", FIELD_NAME_AGE:8},
        {FIELD_NAME_ID:5, FIELD_NAME_CATEGORY:animalType.CAT.value,FIELD_NAME_NAME:"CAT-B", FIELD_NAME_AGE:4},
        {FIELD_NAME_ID:6, FIELD_NAME_CATEGORY:animalType.CAT.value,FIELD_NAME_NAME:"CAT-C", FIELD_NAME_AGE:6},
        {FIELD_NAME_ID:7, FIELD_NAME_CATEGORY:animalType.PIG.value,FIELD_NAME_NAME:"PIG-A", FIELD_NAME_AGE:3},
        {FIELD_NAME_ID:8, FIELD_NAME_CATEGORY:animalType.PIG.value,FIELD_NAME_NAME:"PIG-B", FIELD_NAME_AGE:9},
        {FIELD_NAME_ID:9, FIELD_NAME_CATEGORY:animalType.PIG.value,FIELD_NAME_NAME:"PIG-C", FIELD_NAME_AGE:18},
        {FIELD_NAME_ID:10, FIELD_NAME_CATEGORY:animalType.RABBIT.value,FIELD_NAME_NAME:"RAB-A", FIELD_NAME_AGE:4},
        {FIELD_NAME_ID:11, FIELD_NAME_CATEGORY:animalType.RABBIT.value,FIELD_NAME_NAME:"RAB-B", FIELD_NAME_AGE:16},
        {FIELD_NAME_ID:12, FIELD_NAME_CATEGORY:animalType.RABBIT.value,FIELD_NAME_NAME:"RAB-C", FIELD_NAME_AGE:11}
    ]